version: 2
jobs:
  build:
    docker:
      - image: mdphbeta/node-mdph:1.0.3
      - image: circleci/mongo:3.4.2
      - image: selenium/standalone-chrome:latest
    working_directory: /home/ubuntu/mdph
    steps:
      - checkout

      - restore_cache:
          key: mdph-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          key: mdph-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/root/.cache/yarn"

      - run:
          name: Run unit tests
          command: yarn test

      - run:
          name: Build package
          command: yarn build

      - run:
          name: Run test server
          command: yarn circle-server
          background: true

      - run:
          name: Run e2e tests
          command: yarn circle-e2e

      - add_ssh_keys

      - deploy:
          name: Deploy for branch master only
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pm2 deploy pm2.json production
            fi
